### ISSUE TITLE
lightgallery is not working

### ISSUE THREAD

**Issue by SubrataM3** [oupala/apaxy#132]
**Describe the bug**
lightgallery feature is not working (Apache/2.2.34).

**To Reproduce**
1. within your data directory run
`docker run -dit --name apaxy-apache2.2-debian -p 80:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:2.2`
2. modify `apaxy.config` and run `./apaxy-configure.sh`

**Expected behavior**
lightgallery feature should work.

**Demo**
[link](https://framabin.org/p/?0e4de7a91a37e4dc#9Zi+9pqRuddPsI7DKroYAvkwPJsjD4Xu1deawnLG9dk=)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Chrome 
 - Version: 75.0.3770.80

**Additional information**
Please check my demo link. I can see that lightgallery related js and css are loaded correctly.
P.S - Apaxy is not working for apache 2.4 ([docker](https://github.com/oupala/apaxy/blob/develop/Dockerfile)) which is on this repository. But it is working with apache 2.2 (Docker).

**Comment by oupala** [comment]
I don't understand your *To Reproduce* section because you're using the standard httpd:2.2 docker image, not an image that contains the apaxy software.

Could you please check this issue?

**Comment by SubrataM3** [comment]
> I don't understand your _To Reproduce_ section because you're using the standard _httpd:2.2_ docker image, not an image that contains the apaxy software.
> 
> Could you please check this issue?

Hi, i had mentioned this before. So i took httpd 2.2 image and configured using your apaxy-configure.sh script.  I hope i am clear now.

> P.S - Apaxy is not working for apache 2.4 (docker) which is on this repository. But it is working with apache 2.2 (Docker).

**Comment by oupala** [comment]
I have fixed a small js problem and the docker image is now working in the `hotfix` branch.

Steps to reproduce:

- clone the repo
- change the `apaxy.config` file to set `enableGallery=true`
- build the docker image `docker build -t apaxy .`
- launch the container by `docker-compose up`
- browse the files and click on `example.gif`, see that the gallery is enabled

No image are displayed as all *example* files are empty files. But this should work with real image file.

Could you please test this `hotfix` branch so that I can release a new version?

**Comment by SubrataM3** [comment]
Nope, it does not work, the hyper links are broken.

**Comment by oupala** [comment]
Did you checked out the `hotfix` branch? I forgot to add this step in my previous comment (I've just added it now).

**Comment by SubrataM3** [comment]
> Did you checked out the `hotfix` branch? I forgot to add this step in my previous comment (I've just added it now).

Yep, sorry, i did not carefully read the text above `Steps to reproduce:` and blindly followed the instruction.
And yeap, its working fine.  👍

**Comment by oupala** [comment]
I've just released a new version 2.1.3 of apaxy which does fix the bug that @SubrataM3 has found.

I had to remove some js code (in commit afa2e5197064f9eac7086a0025c12d956ef4ed7e) that was creating the bug.

This piece of code was added by @hazcod on 15 Jul 2016 in commit 7d81d956b90b88613ba0fc159596ce396a76d954 (and @wblondel was already warning that it was breaking links for him, probably under some circonstances). Then it was later modified by @vivernet on 10 Mar 2018 in commit 04b185d702e1429efb9efa84d10c67243e4ad993.

I add this comment to remember why I removed this js code, and because I don't know why was this piece of code for.

I suspect that I was needed with apache < 2.4 and is no longer useful with apache >= 2.4.
