### ISSUE TITLE
Lightgallery Plugins

### ISSUE THREAD

**Issue by thomasskull666** [oupala/apaxy#151]
I would like to add lightgallery plugins to the gallery functionality but am unsure how to do so. Is this planned in a future release or is there guidance that you can give on how to accomplish this? Thanks.

**Comment by thomasskull666** [comment]
I am aware, I am asking specifically about the lightgallery plugins (lg-rotate, lg-zoom, etc.). Is there documentation available for these? API reference [here](https://sachinchoolur.github.io/lightgallery.js/docs/api.html) for 1.x.

**Comment by oupala** [comment]
There is no specific documentation about LightGallery settings in Apaxy. You can check the official LightGallery documentation, and then [dive into the code of Apaxy](https://github.com/oupala/apaxy/blob/cb96aa8f146ace8f95dfdcb83f96b91253376261/apaxy/theme/apaxy-lightgallery.js#L7-L15) in order to configure LightGallery the way you want.

**Comment by thomasskull666** [comment]
OK thank you for the information, that is what I suspected but figured I would check anyway.
