### ISSUE TITLE
Minimise html/css/js

### ISSUE THREAD

**Issue by Filip98** [oupala/apaxy#154]
**Is your feature request related to a problem? Please describe.**
There are some code blocks that do nothing (presumably to easily find what to edit when doing customization's), for example:
https://github.com/oupala/apaxy/blob/98ebe81fbdf4040ee403b227eb2ba479c7b78822/apaxy/theme/style.css#L172-L174
and here:
https://github.com/oupala/apaxy/blob/98ebe81fbdf4040ee403b227eb2ba479c7b78822/apaxy/theme/apaxy.js#L77-L80

This technically slows down the page loading but for a better effect all of the white space should be removed, and a good minifier will remove empty blocks as well 

e.g Using https://cssminifier.org/ I was able to reduce style.css from 8.3KiB to 6.0KiB and it removed the empty block

**Describe the solution you'd like**
Since the theme is basically preprocessed when installing, terser (for js) or some other tool could be invoked in the script to minify the files, maybe into new ones e.g style.min.css and to keep the originals

**Describe alternatives you've considered**
Maybe just including the minified versions in the repo and potentially defaulting to them

**Comment by Filip98** [comment]
Hey @oupala, I think the solution to have non minified versions of files turn into minified versions is a pretty good compromise allowing for customization and readability before and after installation.

Alternatively maybe a coding style could be adopted that uses less whitespace, all the indentation in the html files could be removed as they're pretty small

**Comment by oupala** [comment]
apaxy is a piece of software that should be pretty ready to use without a full installation process. That's why I want to keep an unoptimized version of files by default.

Indentation of html files is usefull for readability. Removing them is not a solution.

The only solution that I'm seeing is adding an optional step in the configuration script `apaxy-configure.sh` that could be used to minify resource files. However, this script is currently mainly doing some `mv` and some `sed` commands. Do you know any way to minify css, js and html file with bash?

**Comment by oupala** [comment]
Closing issue after long inactivity.

Feel free to reopen if you want to.
